spring.datasource.url=jdbc:sqlserver://${DB_HOST}:${DB_PORT:1433};databaseName=${DB_NAME:InventorioDB};encrypt=true;trustServerCertificate=false
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver


spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000

logging.level.root=INFO
logging.level.com.catalogo.inventory=INFO
logging.level.org.hibernate.SQL=WARN

spring.jpa.show-sql=false

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=when-authorized