spring.application.name=inventario-service

spring.profiles.active=local

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server.port=${INVENTORY_SERVICE_PORT:8082}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

logging.level.com.catalogo.inventarioservice=DEBUG
logging.level.org.hibernate.SQL=DEBUG